package main

import "GoFirst/mobula"

func main()  {
	//有且只有一个main包和main函数
	//fmt.Println("Hello World")
	//mygolang.Mygolang()
	//mycollection.MyCollection()
	//mycollection.MySort()
	//myfunc.Myfunc()
	//n, s :=0x1234, "Hello World";
	//println(s,n)
	//mygolang.Mygolang()
	//mycollection.MyCollection()
	//myoop.Myoop()
	//myoop.MyInterface()
	//myGoroutine.MyGoroutine()
	//mypackage.MyPackage()
	//goandc.Mygoandc()
	//myapi.MyApi()
	//myio.MyIo()
	//http.MyHttp()
	//mytcp.MyTcpServer()
	//mytcp.MyTcpClient()
	//mytcp.MyUdpServer()
	//mytcp.MyTcpClient()
	//myref.Myref()
	//goandc.Mygoandc()
	//goandc.Mygoandcndc()
	//mygoroutine.Mygoroutine()
	//sql.MysqlTest()
	//myGoroutine.ChTest()
	//Test.Test()
	//Utils.UtilTest()
	//goProject.StartServer(":8080")
	//goProject.XmlParse()
	//tomcat.FinalTest()
	//tomcat.XmlParse("/home/zw/go/src/GoFirst/goProject/tomcat/study.xml")
	//	tomcat.HtmlBody("/home/zw/go/src/GoFirst/goProject/tomcat/","myhtml.html")
	//myGoroutine.MySelect()
	//tomcat.RedisTest()
	//tomcat.ConnTest()
	//ticketMaster.TStart()
	//ticketMaster.TClient()
	//ticketMaster.QueueTest()
	//fmt.Print("111")
	//mobula.Transform2()
	//mobula.Unmarshal()
	//mobula.Test()
	mobula.MergeTransform()
	//mobula.PbulishTransform()
	//mobula.GetGroups()
	//mobula.TestT()
}